#!/bin/bash

if [ "$1" == "" ]; then
	echo "ip requierd"
	exit 1
fi

nmcli c mod etho0 ipv4.addresses $1/24 ipv4.gateway 10.10.10.1 ipv4.dns "10.10.10.1 8.8.8.8" ipv4.method manual
systemctl restart network
